9 implement remaining functions
quantumion/PyVCAM pull request #14
Opened 2023-03-27 15:25 UTC by CKevin9

Implement remaining functions that are not specified in Priority 1 or 2 in [HighPriorityPyVCAMMethods.docx](https://uofwaterloo.sharepoint.com/:w:/r/sites/tm-sci-quantumion/Shared%20Documents/Control%20System/Control%20Software/HighPriorityPyVCAMMethods.docx?d=wd6c0270b724c4ec48939526400baba63&csf=1&web=1&e=mdoHcr)

2023-03-28 17:25 UTC, collineps requested changes
Good work. Please make some clarifying changes to the comments/documentation.

2023-03-28 17:25 UTC, collineps commented on src/pyvcam/driver.py
> +        raise AttributeError("Function is not supported by the Prime BSI Camera.")
What happens if you actually make the call to the underlying library? If it fails in this same way, no need to intervene to throw our own error.

2023-03-28 17:25 UTC, collineps commented on src/pyvcam/driver.py
> +        raise AttributeError("Function is not supported by the Prime BSI Camera.")
Similar - if the failure mode is the same, may as well pass the argument along and let the other library throw the error.

2023-03-28 17:25 UTC, collineps commented on src/pyvcam/driver.py
> +        Changes clear mode. Refer to :func:`clear_modes` for the available clear modes. Exact case matching is **required**.
The function referenced does not list the available clear mode. The modes appear to be in this comment. Also, what's a clear mode?

2023-03-28 17:25 UTC, collineps commented on src/pyvcam/driver.py
> +        :param param_name: A string name for the post-processing parameter. Refer to :func:`post_processing_table` for parameter names.
The referenced function does not have the feature/parameter names listed in the comments.

2023-03-28 17:25 UTC, collineps commented on src/pyvcam/driver.py
> +        :param param_name: A string name for the post-processing parameter. Refer to :func:`post_processing_table` for parameter names.
The referenced function does not have the feature/parameter names listed in the comments.

2023-03-28 17:25 UTC, collineps commented on src/pyvcam/driver.py
> +        Refer to :func:`exp_out_modes` for the available exposure out modes.
The referenced function does not have the modes listed in the comments.

2023-03-28 17:25 UTC, collineps commented on src/pyvcam/driver.py
> +        Changes exposure out mode. Refer to :func:`exp_out_modes` for the available exposure out modes. Exact case matching is **required**.
The referenced function does not have the modes listed in the comments. In fact, they appear to be in the comments for this function.

2023-03-28 17:25 UTC, collineps commented on src/pyvcam/driver.py
> +        Changes programmable scan mode. Refer to :func:`prog_scan_modes` for the available programmable scan modes.
The referenced function does not have the modes listed in the comments. In fact, they appear to be in the comments for this function.

2023-03-28 17:25 UTC, collineps commented on src/pyvcam/driver.py
> +        Refer to :func:`prog_scan_dirs` for the available programmable scan directions.
The referenced function does not have the modes listed in the comments.

2023-03-28 17:25 UTC, collineps commented on src/pyvcam/driver.py
> +        Changes programmable scan mode. Refer to :func:`prog_scan_dirs` for the available programmable scan directions.
The referenced function does not have the modes listed in the comments. They appear to be in the comments for this function.

2023-03-28 17:25 UTC, collineps commented on src/pyvcam/driver.py
> +        :return: scan direction reset state of camera. The parameter is used with alternate scan directions (down-up) to reset the direction with every acquisition.
Please put a description of the function in the body of the comment.

2023-03-28 17:25 UTC, collineps commented on src/pyvcam/driver.py
> +        :return: The scan line delay. The parameter access mode depends on the :func:`get_prog_scan_mode` selection.
Please put a description of the function in the body of the comment.

2023-03-28 17:25 UTC, collineps commented on src/pyvcam/driver.py
> +        :return: The scan width. The parameter access mode depends on the :func:`get_prog_scan_mode` selection.
Please put a description of the function in the body of the comment.

2023-03-28 17:25 UTC, collineps commented on src/pyvcam/driver.py
> +        :return: The scan line delay. The parameter access mode depends on the :func:`get_prog_scan_mode` selection.
`get_prog_scan_mode` is a getter - there is no selection. Please clarify.

2023-03-28 17:25 UTC, collineps commented on src/pyvcam/driver.py
> +        Changes the scan line delay. The parameter access mode depends on the :func:`get_prog_scan_mode` selection.
`get_prog_scan_mode` is a getter - there is no selection. Please clarify.

2023-03-28 17:25 UTC, collineps commented on src/pyvcam/driver.py
> +        :return: The scan width. The parameter access mode depends on the :func:`get_prog_scan_mode` selection.
`get_prog_scan_mode` is a getter - there is no selection. Please clarify.

2023-03-28 17:25 UTC, collineps commented on src/pyvcam/driver.py
> +        Changes the scan width. The parameter access mode depends on the :func:`get_prog_scan_mode` selection.
`get_prog_scan_mode` is a getter - there is no selection. Please clarify.

2023-03-28 17:25 UTC, collineps commented on src/pyvcam/driver.py
> +        :return: The camera's current ADC offset value. Only CCD camera's have ADCs (analog-to-digital converters).
Please put a description of the function in the body of the comment.

2023-03-28 17:25 UTC, collineps commented on src/pyvcam/driver.py
> +    def set_vtm_exp_time(self, value: int) -> None:
Please put a description of the function in the body of the comment.

2023-03-28 17:25 UTC, collineps commented on src/pyvcam/driver.py
> +        :return: The last acquisition's clearing time as reported by the camera in microseconds.
Please put a description of the function in the body of the comment.

2023-03-28 17:25 UTC, collineps commented on src/pyvcam/driver.py
> +        :return: True if meta data is enabled, False otherwise.
Please put a description of the function in the body of the comment.

2023-03-28 19:27 UTC, CKevin9 commented on src/pyvcam/driver.py
> +        Changes clear mode. Refer to :func:`clear_modes` for the available clear modes. Exact case matching is **required**.
Descriptions of clear mode (and other configuration in the whole script) is available on the [Prime BSI User Manual](https://www.photometrics.com/wp-content/uploads/2019/11/BSI-Manual_08042020.pdf)

2023-03-29 13:55 UTC, collineps approved these changes
Well done. As a reminder, going forward please prepend the number of the issue that you are working on to the name of the branch you use for that work.

2023-03-29 13:58 UTC, merged