1 artiq integration
quantumion/PyVCAM pull request #2
Opened 2023-02-27 17:30 UTC by CKevin9

2023-02-28 20:14 UTC, collineps requested changes
There are a few things to touch up around the controller and setup scripts for correctness, reusability, and clarity. Otherwise, mostly minor formatting changes. Please also make the following changes:

- Move `aqctl_pyvcam.py` into the `src` folder. All project source code should live inside this folder.
- Consider moving `aqctl_pyvcam.py` into the `src/pyvcam` folder and renaming it to `__main__.py`. This will enable a user to boot up the controller by calling `python -m pyvcam` while still allowing the package to be imported and used by other scripts. You may find this more convenient - your call.
- Update the README to reflect the addition of the controller. Also update the installation instructions to make them more explicit/correct.

Good work! Really happy to see this working.

2023-02-28 20:14 UTC, collineps commented on setup.py
> +pip.main(['install', 'opencv-python'])
```suggestion
```
`opencv-python` is never used in the controller script. If it's not used elsewhere in the package, then we don't need to use it here.

More broadly, we shouldn't be calling `pip` inside the `setup.py` script. Adding the package name to the `install_requires` argument in `setup()` accomplishes this. Remove the stale commented code here, since we will not use this installation method.

Make sure to test installation with this modified setup script!

2023-03-13 16:57 UTC, collineps requested changes
Making progress! Really good work getting this code working. Please make the changes indicated in the comments, as well as the following:
- Update the project metadata in the `setup.py` script.
- Look into adding the ability to selectively install different versions of the package depending on whether or not the user wants an NDSP with [optional dependencies](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies).
- Recheck the formatting of the comments. Be consistent in the formatting across all comments (e.g. ending comment/parameter description lines with/without periods).
- Consider making more extensive use of logging. In particular, symmetric operations should have both operations supported. If `open` is logged, log `close` as well, for example.

2023-03-13 16:57 UTC, collineps commented on src/pyvcam/__main__.py
> +    parser.add_argument("-d", "--desc", default=None, help="PyVCAM Wrapper. See documentation at https://github.com/Photometrics/PyVCAM")
What is happening with this argument? This kind of information is usually displayed using the `-h --help` flags.

2023-03-13 16:57 UTC, collineps commented on src/pyvcam_driver.py
> +        Calls the pvc.abort function that aborts acquisition.
More concise description.

2023-03-13 16:57 UTC, collineps commented on src/pyvcam_driver.py
> +    def readout_port(self) -> int:
```suggestion
    def get_readout_port(self) -> int:
```
For symmetry with `set_readout_port`.

2023-03-13 16:57 UTC, collineps commented on src/pyvcam_driver.py
> +                     timeout_ms: int=WAIT_FOREVER, interval: int=None) -> list[list[list[int]]]:
```suggestion
    def get_sequence(self, num_frames: int, exp_time: int=None, timeout_ms: int=WAIT_FOREVER, interval: int=None) -> list[list[list[int]]]:
```
Formatting.

2023-03-13 16:57 UTC, collineps commented on src/pyvcam_driver.py
> +        rapid-succession for the specified number of frames
```suggestion
        Calls the pvc.get_frame function with the current camera settings in rapid-succession for the specified number of frames.
```
Formatting.

2023-03-13 16:57 UTC, collineps commented on src/pyvcam_driver.py
> +                   stream_to_disk_path: str=None) -> None:
```suggestion
    def start_live(self, exp_time: int=None, buffer_frame_count: int=16, stream_to_disk_path: str=None) -> None:
```
Formatting.

2023-03-13 16:57 UTC, collineps commented on src/pyvcam_driver.py
> +                   copyData: bool=True) -> tuple[dict, float, int]:
```suggestion
    def poll_frame(self, timeout_ms: int=WAIT_FOREVER, oldest_frame: bool=True, copy_data: bool=True) -> tuple[dict, float, int]:
```
Formatting. Also, follow Python variable name convention.

2023-03-13 16:57 UTC, collineps commented on src/pyvcam_driver.py
> +        return self.cam.poll_frame(timeout_ms, oldestFrame, copyData)
```suggestion
        return self.cam.poll_frame(timeout_ms, oldest_frame, copy_data)
```
Follow Python variable name convention.

2023-03-13 16:57 UTC, collineps commented on src/pyvcam_driver.py
> +        Returns the last acquisition's post-trigger delay reported by the camera in ms.
```suggestion
        Returns the last acquisition's post-trigger delay reported by the camera in milliseconds.
```
More precise description.

2023-03-13 16:57 UTC, collineps commented on src/pyvcam_driver.py
> +        Returns the last acquisition's pre-trigger delay reported by the camera in ms.
```suggestion
        Returns the last acquisition's pre-trigger delay reported by the camera in milliseconds.
```
More precise description.

2023-03-13 16:57 UTC, collineps commented on src/pyvcam_driver.py
> +        Returns the scan line time in ns.
```suggestion
        Returns the scan line time in nanoseconds.
```
More precise description.

2023-03-13 16:57 UTC, collineps commented on src/pyvcam_driver.py
> +    def speed_table_index(self) -> int:
```suggestion
    def get_speed_table_index(self) -> int:
```
For symmetry with `set_speed_table_index`.

2023-03-13 16:57 UTC, collineps commented on src/pyvcam_driver.py
> +    def temp_setpoint(self) -> float:
```suggestion
    def get_temp_setpoint(self) -> float:
```
For symmetry with `get_temp_setpoint`.

2023-03-13 16:57 UTC, collineps commented on src/pyvcam_driver.py
> +    def temp(self) -> float:
Suppose it's best not to break the API given by the underlying module when possible, but this kind of senseless truncation is frustrating to me. Naming this function `temperature` is more explicit and really not less usable. Still, we can leave it.

2023-03-13 16:57 UTC, collineps commented on src/pyvcam_driver.py
> +        return self.cam.trigger_table
```suggestion
        return self.cam.trigger_table
 
```
Add terminating newline.

2023-03-13 16:57 UTC, collineps commented on src/pyvcam/__main__.py
> +        pvc.uninit_pvcam()
Can `pvc.uninit_pvcam()` live inside the `close()` function?

2023-03-13 16:57 UTC, collineps commented on src/pyvcam/__main__.py
> +    common_args.simple_network_args(parser, 3249)
What does this function do? Is `3249` the set port, or is it the default port? Weirdly, the [sipyco docs](https://m-labs.hk/artiq/sipyco-manual/#module-sipyco.common_args) don't seem to include this function.

2023-03-13 16:57 UTC, collineps commented on setup.py
>  # TODO add checks for if a package is already installed and if so don't install it, if it is installed and up to date give option to update or not
Remove all stale comments/commented code.

2023-03-13 16:57 UTC, collineps commented on README.md
> +self.pyvcam.set_gain(1)
I like the help for setting up the control. Instead of overriding the help, put in a comparison between the bare class and the driver wrapper. A table may be useful.

2023-03-13 16:57 UTC, collineps commented on README.md
> +        "command": "python ~/Projects/QuantumIon-ARTIQ-System/pyvcam/aqctl_pyvcam.py -p {port}"
Please replace this with a generic path-to-file placeholder. This code will live in different locations on different machines for different users.

2023-03-13 16:57 UTC, collineps commented on README.md
> +6. Activate the PyVCAM setup process by running ```python setup.py install```.
Double-check this setup advice:
- If we set up the install script correctly, the user should not need to manually install dependent packages.
- Rephrase so that it doesn't appear that the installation _depends_ on a virtual environment. Using some sort of environment manager is a best practice, not a requirement (hopefully).
- Installation using `python setup.py install` is outdated. Does this package work with the more modern `pip install .`?

2023-03-13 16:57 UTC, collineps commented on README.md
> +* Navigate to ```/src/``` folder and run ```python -m pyvcam```.
After installation, the user should be able to call the module using this invocation from _anywhere_ (as long as the package is correctly installed in the current environment). Is this true for this package? If not, why?

2023-03-13 16:57 UTC, collineps commented on README.md
> +* You can now run files with the ```artiq_run``` command.
```suggestion
```
These instructions are a little ambiguous/specific to our ARTIQ setup. I think we can omit them and delegate the instructions for running ARTIQ code to other projects.

2023-03-14 15:16 UTC, CKevin9 commented on src/pyvcam_driver.py
> +    def exp_time(self) -> int:
Controller compiles but AttributeError is returned in ARTIQ experiment.

2023-03-14 15:33 UTC, CKevin9 commented on src/pyvcam/__main__.py
> +    common_args.simple_network_args(parser, 3249)
It's the default port that ARTIQ uses in their [tutorial on how to setup an NDSP](https://m-labs.hk/artiq/manual/developing_a_ndsp.html#the-driver-and-controller), and it seems no devices are using it in our lab either. Is there another different preferred port?

2023-03-14 15:44 UTC, CKevin9 commented on README.md
> +6. Activate the PyVCAM setup process by running ```python setup.py install```.
Yes, it does work with `pip install .`

2023-03-15 14:49 UTC, collineps commented on src/pyvcam/__main__.py
> +    common_args.simple_network_args(parser, 3249)
Not as far as I know, but we will need to make multiple NDSPs. Having the ability to programmatically set the port will be good. Looks like this already supports that capability based on the fact that the device_db entry seems to treat it like a variable.

2023-03-15 15:00 UTC, collineps commented on README.md
> +6. Activate the PyVCAM setup process by running ```pip install .```.
```suggestion
1. Clone this repository into your Projects folder with the command ```git clone git@github.com:quantumion/PyVCAM.git```.
* **Note:** The following steps (2-3) may be skipped if installation is to be done on disk - virtual environment usage is not a requirement.
2. Navigate into your PyVCAM folder and create a virtual environment with ```virtualenv venv```. 
3. Activate your virtual environment with ```source venv/bin/activate```.
4. Install PyVCAM by running ```pip install .```.
```
The user should not have to install `sipyco` manually if out set up script is correct. Does the set up script in fact not run correctly if the user has not previously installed `sipyco` into their environment?

2023-03-15 15:01 UTC, collineps commented on README.md
> +* Add flags to specify parameters. Add ```-h``` to see a list of flags.
Double-check: does this actually work as expected (even with the description argument removed)?

2023-03-15 15:03 UTC, collineps commented on README.md
> +frame = self.pyvcam.get_frame(exp_time=20)
Please add a comparison table similar to the one you have in the Changing Settings Example section below.

2023-03-15 15:06 UTC, collineps commented on README.md
> +        "host": "::1",
Please add comment indicating that the host must be changed if running the controller on a separate host from the one running the ARTIQ experiment (i.e. not the `localhost`).

2023-03-15 15:07 UTC, collineps commented on README.md
> +* A camera object self.pyvcam has already been created
```suggestion
* Given that a camera object cam/self.pyvcam has already been created:

```
Account for both columns in table.

2023-03-15 15:09 UTC, collineps commented on setup.py
Please update the metadata in the `setup` functions. Specifically, the `author`, `author_email`, `url`, and `description` fields can be modified/added to. Do not remove authors and emails, but add yourself/us to them. The URL should be the current project URL. Description should acknowledge the changes we've made to the package.

2023-03-15 15:10 UTC, collineps commented on setup.py
> +      py_modules=['pyvcam.constants', 'pyvcam.driver'],
Is `driver` a necessary entry here? If so, why?

2023-03-15 15:11 UTC, collineps commented on src/pyvcam/driver.py
> +        print('del function called')
```suggestion
```
Unnecessary statement.

2023-03-15 15:14 UTC, collineps commented on src/pyvcam/__main__.py
> +from pyvcam import pvc
```suggestion
```
Unused dependency.

2023-03-15 15:16 UTC, collineps commented on src/pyvcam/driver.py
> +    def set_exp_mode(self, key_or_value: int) -> None:
If the default behavior of this field is to accept a string (as indicated in the `README`), why change the interface to accept an `int` key? The string method is much more explicit while the integer key obscures meaning in the code (even if the explanation is available in comments/docs). It is also symmetric with the `get_exp_mode` method.

If there isn't a compelling technical reason for using the `int`, please implement accepting the string argument.

2023-03-15 15:17 UTC, collineps commented on src/pyvcam/driver.py
> +    def set_exp_res(self, key_or_value: int) -> None:
Similarly - why integer key over string key? Use string if there is not a good reason for integer.

2023-03-15 15:18 UTC, collineps commented on src/pyvcam/driver.py
> +        Calls the pvc.get_frame function with the current camera settings in rapid-succession for the specified number of frames.
Please modify this comment to describe the performance of the function (what it does) rather than the underlying technical details (what it calls).

2023-03-15 15:20 UTC, collineps commented on src/pyvcam/driver.py
> +        Changes binning. A single value wills et a square binning.
Please fix this mangled comment (`wills et a square`).

2023-03-15 15:20 UTC, collineps commented on src/pyvcam/driver.py
> +        Binning cannot be changed directly on the camera; but is used for setting up
```suggestion
        Binning cannot be changed directly on the camera, but is used for setting up 
```

2023-03-15 15:21 UTC, collineps commented on README.md
>  This captures a single image with a 20 ms exposure time and prints the values of the first 5 pixels.
```suggestion
This captures a single image with a 20 millisecond exposure time and prints the values of the first 5 pixels.

```
Explicit description.

2023-03-15 15:22 UTC, collineps commented on src/pyvcam/driver.py
> +        return self.cam.poll_frame(timeout_ms, oldest_frame, copy_data)
```suggestion
    def poll_frame(self, timeout: int=WAIT_FOREVER, oldest_frame: bool=True, copy_data: bool=True) -> tuple[dict, float, int]:
        """
        Returns a single frame as a dictionary with optional meta data if available. 
        This method must be called after either stat_live or start_seq and before either abort or finish. 
        Pixel data can be accessed via the pixel_data key. Available meta data can be accessed via the meta_data key.

        If multiple ROIs are set, pixel data will be a list of region pixel data of length number of ROIs. 
        Meta data will also contain information for each ROI.

        Use set_param(constants.PARAM_METADATA_ENABLED, True) to enable meta data.

        :param timeout: Duration to wait for new frames in milliseconds.
        :param oldest_frame: If True, the returned frame will the oldest frame and will be popped off the queue. 
                            If False, the returned frame will be the newest frame and will not be removed from the queue.
        :param copy_data: Selects whether to return a copy of the numpy frame which points to a new buffer, or the original numpy frame which points to the
                         buffer used directly by PVCAM. Disabling this copy is not recommended for most situations. Refer to PyVCAM Wrapper.md for more details.

        :return: A dictionary with the frame containing available meta data and 2D np.array pixel data, frames per second and frame count.
        """
        return self.cam.poll_frame(timeout, oldest_frame, copy_data)
```
Change odd variable name.

2023-03-15 15:24 UTC, collineps commented on src/pyvcam/driver.py
> +        the temperature that a camera will attempt to keep it's temperature (in Celsius) at.
```suggestion
        the temperature at which a camera will attempt to stabilize it's temperature (in Celsius).
```
Clarity.

2023-03-15 15:55 UTC, CKevin9 commented on README.md
> +6. Activate the PyVCAM setup process by running ```pip install .```.
Yes, sipyco needs to be installed into environment first, else `setup.py` returns
```ERROR: Could not find a version that satisfies the requirement sipyco (from pyvcam) (from versions: none)
ERROR: No matching distribution found for sipyco```
changed setup.py to include git link such that separate installation is not needed

2023-03-15 15:57 UTC, CKevin9 commented on README.md
> +* Add flags to specify parameters. Add ```-h``` to see a list of flags.
Yes

2023-03-15 19:46 UTC, collineps approved these changes
Great work. Please address these small documentation changes and then we're good to go.

2023-03-15 19:46 UTC, collineps commented on README.md
> +* **Note:** The following steps (2-3) may be skipped if installation is to be done on disk - virtual environment usage is not a requirement.
```suggestion
* **Note:** The following steps (2-3) may be skipped if installation is to be done in the default/user specified environment- virtual environment usage is not a requirement.
```
Clarity.

2023-03-15 19:46 UTC, collineps commented on README.md
> +self.pyvcam.set_gain(1)             # sets gain value to 1
Please add a comparison usage table here as well.

2023-03-15 19:46 UTC, collineps commented on setup.py
> +      author_email='Steve.Bellinger@Teledyne.com, k377chen@uwaterloo.ca, collin.epstein@uwaterloo.ca',
```suggestion
      author_email='Steve.Bellinger@Teledyne.com, k377chen@uwaterloo.ca, cepstein@uwaterloo.ca',
```
Correction.

2023-03-15 19:46 UTC, collineps commented on src/pyvcam/driver.py
> +        raise NotImplementedError("Function should not be explicitly called; already implemented during initialization.")
```suggestion
        raise NotImplementedError("Function should not be explicitly called; already called as needed during initialization.")
```
Clarity.

2023-03-15 20:09 UTC, collineps approved these changes

2023-03-15 20:10 UTC, merged