5 Sphinx integration
quantumion/PyVCAM pull request #6
Opened 2023-03-06 18:37 UTC by CKevin9

2023-03-22 15:08 UTC, collineps requested changes
This is excellent work! Thanks for leading the way on this. Please make the changes indicated in the review, as well as:

- [ ] Add a section in the README with instructions on how to build the documentation.
- [ ] While you're in the README, please update the `get_exp_modes` example to use the string key (we support that now, right?). Looks like we missed that in the last PR.

Also, going forward, please put a description of the changes made in the PR as the initial comment when you open the PR.

2023-03-22 15:08 UTC, collineps commented on doc/source/conf.py
> +copyright = '2023, QuantumIon'
I don't think we actually have a copyright? Please omit this for now. Need to follow up with Crystal and Rajibul on our IP policy.

2023-03-23 15:36 UTC, CKevin9 commented on doc/source/conf.py
> +sys.path.insert(0, '/home/k377chen/Projects/PyVCAM/src/pyvcam/')
Removed import statement - it is unnecessary in our code as we have made PyVCAM an installable

2023-03-23 16:03 UTC, CKevin9 commented on doc/source/usage.rst
> +To save an image to disk, the ``Image`` module from the Python library ``PIL`` has to be imported first.
Yes, `PIL` is replaced by `Pillow`, but the import statement remains the same as shown in the [Pillow documentation](https://pillow.readthedocs.io/en/stable/handbook/tutorial.html)

2023-03-23 18:14 UTC, collineps commented on doc/source/usage.rst
> +To save an image to disk, the ``Image`` module from the Python library ``PIL`` has to be imported first.
This is true. Just be explicit about which library you're using.

2023-03-23 19:34 UTC, collineps requested changes
Great job. Please make the few frankly pedantic changes requested and then we're good to go!

2023-03-23 19:34 UTC, collineps commented on README.md
> +| `cam.exp_mode = "Internal Trigger"` | `self.pyvcam.set_exp_mode(1792)` or<br/>`self.pyvcam.set_exp_mode("Internal Trigger")`|
```suggestion
| `cam.exp_mode = "Internal Trigger"` | `self.pyvcam.set_exp_mode("Internal Trigger")`|
```
Let's just go ahead and prefer the more explicit option.

2023-03-23 19:34 UTC, collineps commented on docs/Makefile
> +#
```suggestion
```
Who needs it.

2023-03-23 19:34 UTC, collineps commented on docs/make.bat
Is the rest of the package compatible with Windows as well?

2023-03-23 19:34 UTC, collineps commented on docs/source/conf.py
> +release = '0.1'
Hm, the question of versioning is a pretty good one... We'll come back to that.

2023-03-23 19:34 UTC, collineps commented on docs/source/conf.py
> +
```suggestion
```
Formatting.

2023-03-23 19:34 UTC, collineps commented on docs/source/usage.rst
> +To save an image to disk, the ``Image`` class from the Python library ``PIL`` has to be imported first.
```suggestion
One method of saving an image to disk uses the ``Image`` class from ``[pillow](https://python-pillow.org/)``.
```
Only one method of many possible.

2023-03-23 19:34 UTC, collineps commented on src/pyvcam/driver.py
> +            | 1 - One Microsecond
```suggestion
            | 0 - One millisecond
            | 1 - One microsecond
```
Formatting.

2023-03-23 19:53 UTC, CKevin9 commented on src/pyvcam/driver.py
> +            | 1 - One Microsecond
If the user wishes to change this setting by key strings, they will have to enter the key exactly, including the uppercase M's.
Of course, we could use Python's `.title()` function to ignore upper/lowercase user input, but the problem is replicated in the `set_exp_mode()` function where `Internal Trigger` and `Edge Trigger` keys are in title case, but `Trigger first` is only capitalized. These values are intrinsic to the `camera.py` file which reads from the `pvc` wrapper and cannot be changed (which is super annoying).

2023-03-24 15:53 UTC, collineps commented on src/pyvcam/driver.py
> +            | 1 - One Microsecond
Ah, I misunderstood! Thank you for the explanation. In that case, of course leave as is. Maybe add a comment here and in `set_exp_mode` that exact case matching is required.

If we want to really take care of the user, we could modify the input as you describe... Might be overkill.

2023-03-27 13:38 UTC, merged